# Switch authentication from variable.properties to Azure Key Vault (yes/no)
useAzureKeyVault=yes

# Datafactory Pipeline Name
pipelineName=

# storageAccountName refers to the Storage Account Name
storageAccountName=

# cosmosdbAccountName refers to the Cosmos DB Account Name
cosmosdbAccountName=

# cosmosdbResourceGroupName refers to the Cosmos DB Resource Group Name
cosmosdbResourceGroupName=

# sqlWarehouse refers to the SQL Warehouse Id in Databricks (used in the Http path value)
sqlWarehouse=

# subscriptionId refers to AZ Subscription ID
# See https://learn.microsoft.com/en-us/cli/azure/account?view=azure-cli-latest#az-account-get-access-token
subscriptionId=

# storageContainerName refers to the Storage Account file system/container name
# See https://learn.microsoft.com/en-us/cli/azure/storage/fs/directory?view=azure-cli-latest#az-storage-fs-directory-exists
storageContainerName=

# resourceGroupName refers to the resource group
# See https://learn.microsoft.com/en-us/cli/azure/datafactory/pipeline-run?view=azure-cli-latest#az-datafactory-pipeline-run-show
resourceGroupName=

# factoryName refers to the DataFactory factory
# See https://learn.microsoft.com/en-us/cli/azure/datafactory/pipeline-run?view=azure-cli-latest#az-datafactory-pipeline-run-show
factoryName=

# serverHostName refers to the backend (Databricks, MSD) Server hostname
serverHostName=

# analyticsWorkspaceId refers to the Log Analytics Workspace Id. Used to query Log Analytics
analyticsWorkspaceId=

# cosmosConnectString_* contains both the AccountEndpoint and AccountKey for Subscription rpu-nprod-careintegration-01
# See https://cosmos.azure.com/?feature.enableAadDataPlane=true%22 and https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/how-to-dotnet-get-started?tabs=azure-cli%2Clinux
cosmosConnectString=

# storageConnectString contains the Connection String for Azure Storage Account
storageConnectString=

# fhirAccountName refers to the Azure Account Name
# See https://learn.microsoft.com/en-us/azure/healthcare-apis/azure-api-for-fhir/get-healthcare-apis-access-token-cli
fhirPaaSService=

# OracleConnectString
oracleConnectString=

# SQLServerConnectString
sqlServerConnectString=

# RestProvider Credentials. "Account Password Group(s)|Account Password Group(s)"
rb_credentials=SAccount ghhjsdkkaa User|SAccount2 091283jgnhasd User|SAccount3 qoweirqiore User|SAccount4 987143297 User|SAccount5 khjkasdiyuqwe User|Administrator uiretouitr Administrator|Administrator2 0980qweeqw Administrator|Administrator3 789798asddasnm,,nm Administrator|Administrator4 bmnbnmasas Administrator|Administrator5 asasdipoioqweeqw Administrator|PowerUser xz,nmcvzx,vcnm PowerUser|PowerUser2 poupiutre PowerUser|PowerUser3 asasmnbbn PowerUser|PowerUser4 908890qweqw,mn,nm PowerUser|PowerUser5 bnmbmassdqq PowerUser
